title: 沐雨橙舟の秘密基地
email: muzhou233@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
keyword: 'MuZhou, MuZhou Blog, OIer, noip'
baseurl: ''
url: 'https://mosarin.tech'


owner:
    name: '化学反应罢了'
    email: 'huafan258@gmail.com'
    bio: ''

# Data
avatar: https://free.picui.cn/free/2026/03/23/69c0bd01221ac.jpg
favicon: /favicon.jpg
music:
    title: But U - NINEONE#乃万
    url: https://music.163.com/song/media/outer/url?id=1459232593.mp3

#Utterances
utterances:
    repo: 'nuyoah-l/nuyoah-l.github.io'
    theme: 'github-light'
    issue-term: 'title'

markdown: kramdown

highlighter: rouge
permalink: pretty
paginate: 16

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - README.md

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Gems
plugins: [jekyll-paginate]
