title: NuyoaH-L
email: nuyoah-l@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
    孤灯不明思欲绝，卷帱望月空长叹
keyword: 'NuyoaH-L, NuyoaH-L Blog, OIer, noip'
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://nuyoah-l.gdata.fun/' # the base hostname & protocol for your site, e.g. http://example.com

# About/contact
owner:
    name: 'NuyoaH-L'
    email: 'nuyoah-l@outlook.com'
    bio: '孤灯不明思欲绝，卷帱望月空长叹'

# Data
avatar: /asserts/img/avatar.jpg
favicon: /favicon.jpg
music:
    title: Eye Water - itsuwari
    url: https://music.163.com/song/media/outer/url?id=1351784375.mp3

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

markdown: kramdown

highlighter: rouge
permalink: pretty
paginate: 16

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - README.md

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Gems
plugins: [jekyll-paginate]

# Gitalk评论插件
comments :
  gitalk :
    clientID : e9d00223edfe5ec618e5  # 获取到的clientID
    clientSecret : d64483e565e51613fb12859774eea1d8a4193607  # 获取到的clientSecret
    repo : pinglun  # 存放评论的仓库
    owner : NuyoaH-L  #仓库的主人
    admin : NuyoaH-L
